cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2022                     # [win]
compiler_version:
  - 18                         # [osx]
  - 13                     # [linux]
cxx_compiler_version:
  - 18                         # [osx]
  - 13                    # [linux]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.13'                # [osx]
pin_run_as_build:
  numpy: x.x
  boost: x.x
  qhull: x.x
  cgap-cpp: x.x
  ann: x.x
  qt-main: x.x
  libpng: x.x
  zlib: x.x
