{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}

package:
  name: openalea.plantgl
  version: {{ version }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --prefix={{ PREFIX }} . -vv

requirements:
  host:
    - python
    - setuptools_scm
    - scikit-build-core
    - numpy
    - qt-main
    - pyqt
    - gmp
    - mpfr
    - sip
    - libpng
    - zlib
    - eigen
    - cgal-cpp
    - qhull
    - ann
    - boost
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - libglu                             # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libx11                        # [linux]

  build:
    - python
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config                        # [linux]
    - binutils_impl_linux-64            # [linux]
    - bison                             # [unix]
    - flex                              # [unix]
    - m2-bison                          # [win]
    - m2-flex                           # [win]
    - menuinst                          # [win]
    - make                              # [unix]

  run:
    - python
    - numpy
    - boost
    - ipython
    - pyopengl
    - pyqglviewer

test:
   requires:
     - pytest
     - matplotlib-base
     - pandas
   imports:
     - openalea.plantgl
     - openalea.plantgl.all
   source_files:
     - test/**
     - share/**
   commands:
     - cd test
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest  # [unix]
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest --ignore=test_shared_data.py  # [win]
