{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}

package:
  name: openalea.plantgl
  version: {{ version }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --prefix={{ PREFIX }} . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools_scm
    - scikit-build-core
    - numpy
    - qt-main
    - pyqt
    - gmp
    - mpfr
    - libpng
    - zlib
    - eigen
    - cgal-cpp
    - qhull
    - ann
    - boost
    - libxcb                             # [linux]
    - pthread-stubs                      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux] # match libqglviewer CDT GL strategy
    - libglu                             # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libx11                        # [linux]

  build:
    - python
    - {{ compiler('cxx') }}
    #- {{ stdlib('cxx') }}
    - cmake
    - pkg-config                        # [linux]
    - binutils_impl_linux-64            # [linux]
    - bison                             # [unix]
    - flex                              # [unix]
    - m2-bison                          # [win]
    - m2-flex                           # [win]
    - menuinst                          # [win]
    - make                              # [unix]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libxext') }}              # [linux]
    - {{ cdt('libselinux') }}           # [linux]
    - {{ cdt('libxdamage') }}           # [linux]
    - {{ cdt('libxfixes') }}            # [linux]
    - {{ cdt('libxxf86vm') }}           # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('expat-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]

  run:
    - python
    - numpy
    - ipython
    - pyopengl
    - pyqglviewer
    - eigen
    - zlib
    - xorg-libxfixes    # [linux]
    - libglu            # [linux]
    # guards for ABI-sensitive libraries
    - {{ pin_compatible('pyqt', max_pin='x.x') }}
    - {{ pin_compatible('boost', max_pin='x.x') }}
    - {{ pin_compatible('cgal-cpp', max_pin='x.x') }}
    - {{ pin_compatible('qhull', max_pin='x.x') }}
    - {{ pin_compatible('ann', max_pin='x.x') }}


test:
   requires:
     - pytest
     - matplotlib-base
     - pandas
   imports:
     - openalea.plantgl
     - openalea.plantgl.all
   source_files:
     - test/**
     - share/**
   commands:
     - cd test
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest  # [unix]
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest --ignore=test_shared_data.py  # [win]
