name: Building Package

on:
  push:
    branches: 
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches: 
      - '**'


jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@main
    with:
      operaoperating-system: ["ubuntu-latest", "macos-13", "windows-latest"]
      python-minor-version: 12
    secrets: 
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
