name: Building Package

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'


jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@label
    with:
      operating-system: '["ubuntu-latest", "windows-latest", "macos-13"]'
      build-options: ""
      label: latest
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
